- hosts: all
  gather_facts: yes
  become: yes
  vars_prompt:
    - name: "backup"
      prompt: "Would you like to backup your node? (yes/no)"
      private: no
    - name: "restore"
      prompt: "Would you like to restore your node? (yes/no)"
      private: no
  roles:
    - lacchain-backup-node
